### ISSUE TITLE
PROXY_URL未生效/设置之后依旧timeout

### ISSUE THREAD

**Issue by Huiyicc** [aurora-develop/Duck2api#28]
国内服务器搭建，docker-compose.yml如下
```
version: '3'

services:
  app:
    image: ghcr.io/aurora-develop/duck2api:latest
    container_name: duck2api
    restart: unless-stopped
    environment:
      - PROXY_URL=http://192.168.1.100:20172
    ports:
      - '40040:8080'
```
已知此代理可以正常访问大多数网站:
![image](https://github.com/user-attachments/assets/6a8a3285-75c4-431d-adc3-3856aef63b8d)

但是使用服务时会一直等待直到timeout
![image](https://github.com/user-attachments/assets/7f4628a6-e1c1-4841-8575-66f7b587b976)

PROXY_URL对应的服务器上搭建的本服务一切正常
![image](https://github.com/user-attachments/assets/61552d05-4969-4c78-9d24-4223e330d93a)
